<?php

/**   
 * Sn name generator
 * The names and first names used in this file,
 * comes from :
 * http://www.planete-senegal.com/senegal/noms_et_prenoms.php
 * http://www.top-names.info/names.php?S=M&P=SEN
 * http://www.top-names.info/names.php?S=W&P=SEN
 * 
 * PHP version 5
 * 
 * @category Utility
 * 
 * @package SN
 * 
 * @author Mouhamed Fadel Diagana <mouhamedfd>
 *
 * @license GPL 3.
 * 
 * @link http://github.com/mouhamedfd
 */

namespace Mouhamedfd\Generator;

/**   
 * Class That generate Random Senegalese Name and FirstName
 * 
 * @category Utility
 * 
 * @package Dmf
 * 
 * @author Mouhamed Fadel Diagana <mouhamedfd@gmail.com>
 *
 * @license GPL 3.
 * 
 * @link http://github.com/mouhamedfd
 */


class SnNameGenerator
{

    public static $names = array(
        'Badiane',
        'Badiatte',
        'Badji',
        'Biagui',
        'Bassène',
        'Bodian',
        'Coly',
        'Diamacoune',
        'Diatta',
        'Diadhiou',
        'Diédhiou',
        'Diémé',
        'Djiba',
        'Ehemba',
        'Goudiaby',
        'Himbane',
        'Mané',
        'Manga',
        'Sagna',
        'Sambou',
        'Sané',
        'Sonko',
        'Tamba',
        'Tendeng',
        'Badiane',
        'Bop',
        'Diaher',
        'Diène',
        'Dieye',
        'Dioh',
        'Diome',
        'Dione',
        'Diong',
        'Dior',
        'Diouf',
        'Dogue',
        'Faye',
        'Kital',
        'Kitane',
        'Mbaye',
        'Mbengue',
        'Ndiaye',
        'Ndiolène',
        'Ndione',
        'Ndong',
        'Ndour',
        'Ngom',
        'Niane',
        'Pouye',
        'Sagne',
        'Sarr',
        'Seck',
        'Sene',
        'Senghor',
        'Seye',
        'Thiandoum',
        'Thiaw',
        'Thiombane',
        'Thione',
        'Tine',
        'Youm',
        'Aïdara',
        'Athie',
        'Aw',
        'Ba',
        'Baby',
        'Baldé',
        'Barro',
        'Barry',
        'Bathily',
        'Boussou',
        'Camara',
        'Cissé',
        'Deme',
        'Dia',
        'Diamanka',
        'Diallo',
        'Diao',
        'Diaw',
        'Dimé',
        'Fassa',
        'Fofana',
        'Gadio',
        'Galadio',
        'Goloko',
        'Kâ',
        'Kane',
        'Maal',
        'Mbow',
        'Lo',
        'Ly',
        'Sall',
        'Seydi',
        'Sow',
        'Sy',
        'Sylla',
        'Tall',
        'Thiam',
        'Wane',
        'Wath',
        'Wone',
        'Yock',
        'Badjinka',
        'Coly',
        'Diandy',
        'Djighaly',
        'Dioma',
        'Diendiame',
        'Nango',
        'Badji',
        'Gomis',
        'Mané',
        'Vieira',
        'Carvalho',
        'Mendy',
        'Mané',
        'Preira',
        'Correia',
        'Basse',
        'Sylva',
        'Da Sylva',
        'Fernandez',
        'Da Costa',
        'Darmanko',
        'Amar',
        'Babou',
        'Diagne',
        'Diakhoumpa',
        'Goumbala',
        'Saady',
        'Sabara',
        'Sougou',
        'Sougoufara',
        'Tandiné',
        'Tandini',
        'Touré',
        'Bakhoum',
        'Diop',
        'Diagne',
        'Gaye',
        'Gueye',
        'Ndoye',
        'Ndiour',
        'Ndir',
        'Samb',
        'Sadio',
        'Vieira',
        'Lopez',
        'Marques',
        'Yalla',
        'Preira',
        'Boubane',
        'Bonang',
        'Bianquinch',
        'Bindian',
        'Bendian',
        'Bangonine',
        'Bapinye',
        'Bidiar',
        'Bangar',
        'Biès',
        'Boye',
        'Cobar',
        'Demba',
        'Dembelé',
        'Diack',
        'Diarra',
        'Diaw',
        'Dieng',
        'Diong',
        'Diop',
        'Fall',
        'Gning',
        'Guène',
        'Hanne',
        'Kane',
        'Kassé',
        'Lèye',
        'Loum',
        'Marone',
        'Mbacké',
        'Mbathié',
        'Mbaye',
        'Mbengue',
        'Mbodj',
        'Mbodji',
        'Mboup',
        'Mbow',
        'Ndao',
        'Ndaw',
        'Nder',
        'Ndiaye',
        'Ndiongue',
        'Ndour',
        'Nger',
        'Niane',
        'Niang',
        'Niass',
        'Niasse',
        'Seck',
        'Sock',
        'Taye',
        'Thiam',
        'Thiongane',
        'Wade',
        'Aïdara',
        'Bathily',
        'Bayo',
        'Camara',
        'Cissé',
        'Cissoko',
        'Coulibaly',
        'Dabo',
        'Demba',
        'Doumbia',
        'Doumbouya',
        'Diabang',
        'Diabira',
        'Diagana',
        'Diakhaby',
        'Diakhaté',
        'Diakité',
        'Dansokho',
        'Diakho',
        'Diarra',
        'Diawara',
        'Dibané',
        'Djimera',
        'Dramé',
        'Doucouré',
        'Fadiga',
        'Faty',
        'Fofana',
        'Gakou',
        'Gandega',
        'Gassama',
        'Kanté',
        'Kanouté',
        'Kébé',
        'Keïta',
        'Koïta',
        'Konaté',
        'Koroboume',
        'Marega',
        'Niangane',
        'Sabaly',
        'Sadio',
        'Sakho',
        'Samassa',
        'Sané',
        'Sawane',
        'Sidibé',
        'Sissoko',
        'Soukho',
        'Soumaré',
        'Tamba',
        'Tambadou',
        'Tambedou',
        'Tandia',
        'Tandian',
        'Tandjigora',
        'Timera',
        'Traoré',
        'Touré',
        'Wagué',
        'Yatéra',
        'Bacourine',
        'Badiete',
        'Bakilane',
        'Baloucoune',
        'Bampoky',
        'Bandagny',
        'Bandiacky',
        'Banko',
        'Baraye',
        'Bathé',
        'Boissy',
        'Cabateau',
        'Campal',
        'Damany',
        'Diompy',
        'Dionou',
        'Dupa',
        'Kabely',
        'Kadiagal',
        'Kadionane',
        'Kagnaly',
        'Kaly',
        'Kanfany',
        'Kanfome',
        'Kanfoudy',
        'Kanpintane',
        'Kantoussan',
        'Kassoka',
        'Kayounga',
        'Keny',
        'Malack',
        'Malèle',
        'Maleumane',
        'Malomar',
        'Malou',
        'Mandika',
        'Mandiouban',
        'Mancabou',
        'Mancore',
        'Mandiamé',
        'Manel',
        'Mansall',
        'Manta',
        'Mantanne',
        'Maty',
        'Mbampassy',
        'Médou',
        'Minkette',
        'Mpamy',
        'Nabaline',
        'Nadiack',
        'Nakouye',
        'Namatane',
        'Nankasse',
        'Nanssalan',
        'Napel',
        'Nataye',
        'Nawoutane',
        'Ndecky',
        'Ndeye',
        'Ndione',
        'Ndô',
        'Ndouikane',
        'Niouky',
        'Ntab',
        'Nzale',
        'Oudiane',
        'Panduppy',
        'Samy',
        'Sanka',
    );
    public static $firstNames = array(
        'Abba',
        'Abdallah',
        'Abdou',
        'Abdoulatif',
        'Abdoulaye',
        'Abdourahmane',
        'Ablaye',
        'Abou',
        'Adama',
        'Adiouma',
        'Agouloubene',
        'Aïdara',
        'Aïnina',
        'Aladji',
        'Alassane',
        'Albouri',
        'Alfa',
        'Alfousseyni',
        'Aliou',
        'Alioune',
        'Allé',
        'Almamy',
        'Amadou',
        'Amara',
        'Amath',
        'Amidou',
        'Ansoumane',
        'Anta',
        'Arfang',
        'Arona',
        'Assane',
        'Asse',
        'Aziz',
        'Baaba',
        'Babacar',
        'Babou',
        'Badara',
        'Badou',
        'Bacar',
        'Baïdi',
        'Baila',
        'Bakari',
        'Ballago',
        'Bamba',
        'Banta',
        'Bara',
        'Bassirou',
        'Bathie',
        'Bayo',
        'Becaye',
        'Bilal',
        'Biram',
        'Birane',
        'Birima',
        'Biry',
        'Bocar',
        'Bodiel',
        'Bolikoro',
        'Boubacar',
        'Boubou',
        'Bougouma',
        'Bouly',
        'Bouna',
        'Bourkhane',
        'Bransan',
        'Cheikh',
        'Chérif',
        'Ciré',
        'Daly',
        'Damé',
        'Daouda',
        'Daour',
        'Demba',
        'Dényanké',
        'Diakhou',
        'Dial',
        'Dialamba',
        'Dialegueye',
        'Dianco',
        'Dicory',
        'Diégane',
        'Diène',
        'Dierry',
        'Diewo',
        'Diokel',
        'Diokine',
        'Diomaye',
        'Dior',
        'Djibo',
        'Djibril',
        'Djiby',
        'Djily',
        'Doudou',
        'Dramane',
        'El Hadj',
        'Elimane',
        'Facourou',
        'Fadel',
        'Falilou',
        'Fallou',
        'Famara',
        'Farba',
        'Fédior',
        'Fatel',
        'Fodé',
        'Fodey',
        'Fodié',
        'Foulah',
        'Galaye',
        'Gaoussou',
        'Gora',
        'Gorgui',
        'Goumbo',
        'Goundo',
        'Guidado',
        'Habib',
        'Hadiya',
        'Hady',
        'Hamidou',
        'Hammel',
        'Hatab',
        'Iba',
        'Ibrahima',
        'Ibou',
        'Idrissa',
        'Insa',
        'Ismaïl',
        'Ismaïla',
        'Issa',
        'Isshaga',
        'Jankebay',
        'Jamuyon',
        'Kader',
        'Kainack',
        'Kalidou',
        'Kalilou',
        'Kambia',
        'Kao',
        'Kaourou',
        'Karamo',
        'Kéba',
        'Khadim',
        'Khadir',
        'Khalifa',
        'Khamby',
        'Khary',
        'Khoudia',
        'Khoule',
        'Kor',
        'Koutoubo',
        'Lamine',
        'Lamp',
        'Landing',
        'Lat',
        'Latif',
        'Latsouck',
        'Latyr',
        'Lémou',
        'Léou',
        'Leyti',
        'Libasse',
        'Limane',
        'Loumboul',
        'Maba',
        'Macky',
        'Macodou',
        'Madia',
        'Madické',
        'Mady',
        'Mactar',
        'Maffal',
        'Maguette',
        'Mahécor',
        'Makan',
        'Malal',
        'Malamine',
        'Malang',
        'Malanh',
        'Malaw',
        'Malick',
        'Mallé',
        'Mamadou',
        'Mamour',
        'Mansour',
        'Maodo',
        'Mapaté',
        'Mar',
        'Massamba',
        'Massar',
        'Masseck',
        'Mbagnick',
        'Mbakhane',
        'Mbamoussa',
        'Mbar',
        'Mbaye',
        'Mébok',
        'Médoune',
        'Meïssa',
        'Mody',
        'Modou',
        'Moktar',
        'Momar',
        'Mor',
        'Mountaga',
        'Moussa',
        'Moustapha',
        'Namori',
        'Ndane',
        'N deupp',
        'Ndiack',
        'Ndiaga',
        'Ndiankou',
        'Ndiasse',
        'Ndiaw',
        'Ndiawar',
        'Ndiaya',
        'Ndiogou',
        'Ndiouga',
        'Ndongo',
        'Ngagne',
        'Ngor',
        'Nguénar',
        'Niakar',
        'Niankou',
        'Niokhor',
        'Nouh',
        'Nouha',
        'Npaly',
        'Ogo',
        'Omar',
        'Opa',
        'Oumar',
        'Oury',
        'Ousmane',
        'Ousseynou',
        'Papa',
        'Pape',
        'Papis',
        'Pathé',
        'Racine',
        'Sadibou',
        'Sacoura',
        'Saër',
        'Sahaba',
        'Saïdou',
        'Seydou',
        'Sakhir',
        'Salam',
        'Salif',
        'Saliou',
        'Saloum',
        'Samba',
        'Samori',
        'Samsidine',
        'Sandigui',
        'Sankoun',
        'Sanokho',
        'Sécouba',
        'Sédar',
        'Sékou',
        'Semou',
        'Senghane',
        'Serigne',
        'Seyba',
        'Seydina',
        'Seydou',
        'Sibiloumbaye',
        'Sidate',
        'Sidy',
        'Siéka',
        'Sihalébé',
        'Sihounke',
        'Silly',
        'Socé',
        'Sogui',
        'Soireba',
        'Solal',
        'Sonar',
        'Souleymane',
        'Soundjata',
        'Sounkarou',
        'Souty',
        'Tafsir',
        'Talla',
        'Tamsir',
        'Tanor',
        'Tayfor',
        'Tekheye',
        'Tété',
        'Thiarro',
        'Thiawlo',
        'Thierno',
        'Thione',
        'Tijane',
        'Tidjane',
        'Toumani',
        'Vieux',
        'Wagane',
        'Waly',
        'Wandifing',
        'Wasis',
        'Woula',
        'Woury',
        'Yacine',
        'Yacouba',
        'Yafaye',
        'Yakou',
        'Yamar',
        'Yankhoba',
        'Yerim',
        'Yero',
        'Yoro',
        'Yougo',
        'Younouss',
        'Youssou',
        'Youssouf',
        'Youssoufa',
        'Abibatou',
        'Aby',
        'Absa',
        'Adama',
        'Adiouma',
        'Adji',
        'Adja',
        'Aïcha',
        'Aïda',
        'Aïssatou',
        'Akinumelob',
        'Alima',
        'Alimatou',
        'Alinsiitowe',
        'Aloendisso',
        'Altine',
        'Ama',
        'Aminata',
        'Amincta',
        'Amy',
        'Anta',
        'Arame',
        'Assa',
        'Assietou',
        'Astou',
        'Ata',
        'Atia',
        'Awa',
        'Awentorébé',
        'Ayimpen',
        'Banel',
        'Batouly',
        'Bigué',
        'Billé',
        'Bincta',
        'Bineta',
        'Binette',
        'Binta',
        'Bintou',
        'Birame',
        'Biram',
        'Boirika',
        'Bougouma',
        'Boury',
        'Bousso',
        'Ciramadi',
        'Codou',
        'Combé',
        'Coudouution',
        'Coumba',
        'Coumboye',
        'Coura',
        'Daba',
        'Dado',
        'Daka',
        'Daly',
        'Debbo',
        'Défa',
        'Dewel',
        'Dewene',
        'Diadji',
        'Diaga',
        'Diakher',
        'Diakhou',
        'Dialikatou',
        'Diama',
        'Diangou',
        'Dianké',
        'Diariatou',
        'Diarra',
        'Diara',
        'Diary',
        'Dibor',
        'Dieourou',
        'Dior',
        'Diouma',
        'Djaly',
        'Djébou',
        'Djeynaba',
        'Dkikel',
        'Djilane',
        'Enfadima',
        'Fabala',
        'Fabinta',
        'Fadima',
        'Fakane',
        'Fama',
        'Fanta',
        'Farmata',
        'Fatima',
        'Fatou',
        'Fatoumatou',
        'Fily',
        'Garmi',
        'Gnagna',
        'Gnilane',
        'Gnima',
        'Gouya',
        'Guignane',
        'Guissaly',
        'Haby',
        'Hawa',
        'Heinda',
        'Holèl',
        'Issate',
        'Kankou',
        'Karimatou',
        'Kenbougoul',
        'Kéwé',
        'Kadiali',
        'Khadija',
        'Khadijatou',
        'Khady',
        'Khar',
        'Khary',
        'Khayfatte',
        'Khoudia',
        'Khoudjedji',
        'Khoumbaré',
        'Kiné',
        'Korka',
        'Laf',
        'Laff',
        'Laffia',
        'Lama',
        'Léna',
        'Lika',
        'Lissah',
        'Liwane',
        'Mada',
        'Madior',
        'Madjiguène',
        'Maguette',
        'Mahawa',
        'Mame',
        'Mamina',
        'Manthita',
        'Marème',
        'Mariama',
        'Mamassa',
        'Mane',
        'Maty',
        'Mayatta',
        'Maymouna',
        'Mbacké',
        'Mbarou',
        'Mbayeng',
        'Mbissine',
        'Mbossé',
        'Meïssa',
        'Mingue',
        'Mouskéba',
        'Nafi',
        'Nbieumbet',
        'Ndebane',
        'Ndella',
        'Ndeye',
        'Ngoundj',
        'Ndiarenioul',
        'Ndiarka',
        'Ndiasse',
        'Ndiaty',
        'Ndiémé',
        'Ndioba',
        'Ndiolé',
        'Ndioro',
        'Ndoffène',
        'Ndombo',
        'Néné',
        'Neyba',
        'Ngoné',
        'Ngosse',
        'Nguenar',
        'Nguissaly',
        'Niakuhufosso',
        'Niali',
        'Nialine',
        'Ningou',
        'Nini',
        'Niouma',
        'Oulèye',
        'Oulimata',
        'Oumou',
        'Oumy',
        'Oureye',
        'Penda',
        'Peye',
        'Peye',
        'Raby',
        'Raki',
        'Rama',
        'Ramata',
        'Ramatoulaye',
        'Rokhaya',
        'Roubba',
        'Roughy',
        'Sadio',
        'Safiétou',
        'Safi',
        'Sagar',
        'Sahaba',
        'Salimata',
        'Salamata',
        'Sanakha',
        'Sarratou',
        'Saoudatou',
        'Sawdiatou',
        'Selbé',
        'Sell',
        'Seynabou',
        'Seyni',
        'Sibett',
        'Siga',
        'Sira',
        'Sirabiry',
        'Soda',
        'Sofiatou',
        'Sofietou',
        'Sokhna',
        'Sonar',
        'Souadou',
        'Soukeye',
        'Soukeyna',
        'Tabara',
        'Tacko',
        'Taki',
        'Tening',
        'Téwa',
        'Tiné',
        'Thiame',
        'Thiomba',
        'Thiony',
        'Thioro',
        'Thioumbane',
        'Tocka',
        'Tokoselle',
        'Toly',
        'Walty',
        'Yadicone',
        'Yacine',
        'Yandé',
        'Yandou',
        'Yaye',
        'Adama',
        'Adiouma',
        'Anta',
        'Birame',
        'Bodiel',
        'Bougouma',
        'Ciré',
        'Daly',
        'Diéry',
        'Khar',
        'Lika',
        'Maguette',
        'Meïssa',
        'Ndiasse',
        'Sagar',
        'Sanou',
        'Yacine',
    );

    public static $manFirstNames = array(
        'Ababacar',
        'Ababacar Sadikh',
        'Abasse',
        'Abba',
        'Abdallah',
        'Abdou',
        'Abdou Aidara',
        'Abdou Aziz Dabakh',
        'Abdou Bodian',
        'Abdou Karim',
        'Abdou Mbacké',
        'Abdou Salam',
        'Abdou Wodod',
        'Abdoul Aziz',
        'Abdoulatif',
        'Abdoulaye',
        'Abdourahmane',
        'Abiba',
        'Abiboulaye',
        'Ablaye',
        'Abo',
        'Abou',
        'Adama',
        'Adama Bodian',
        'Adams',
        'Adiouma',
        'Ado',
        'Agouloubene',
        'Ahmad',
        'Ahmed',
        'Ahmeth Bachir',
        'Aidara',
        'Ainy',
        'Akane Dieng',
        'Aladji',
        'Alassane',
        'Albouri',
        'Alex',
        'Alexis Louis',
        'Alfa',
        'Alfousseyni',
        'Ali Ahmed',
        'Aliou',
        'Aliou Sow',
        'Alioune',
        'Alioune Badara',
        'Alla',
        'Allé',
        'Almamy',
        'Alou',
        'Alpha',
        'Alpha Baba Yaya',
        'Alpha Omar',
        'Alpha Oumar',
        'Alphonse',
        'Alphousseyni',
        'Alseyni',
        'Alune',
        'Aly',
        'Amadou',
        'Amadou Dian',
        'Amadou Moustapha',
        'Amadou Ndongo',
        'Amadou Oury',
        'Amar',
        'Amara',
        'Amath',
        'Amed',
        'Ameth',
        'Amidou',
        'Amisco',
        'Ansoumana',
        'Ansoumane',
        'Anta',
        'Antoine',
        'Aouita',
        'Arfang',
        'Ark',
        'Arona',
        'Ass',
        'Assane',
        'Asse',
        'Auguste',
        'Aziz',
        'Aïdara',
        'Aïnina',
        'Baaba',
        'Baacar',
        'Baba',
        'Babacar',
        'Babagallé',
        'Babou',
        'Baboucar',
        'Bacar',
        'Bacary',
        'Bachir',
        'Badara',
        'Badou',
        'Baila',
        'Bakari',
        'Bakary',
        'Balde',
        'Balde Aliou',
        'Balla',
        'Balla Moussa',
        'Ballago',
        'Bamba',
        'Bane',
        'Banta',
        'Bara',
        'Bass',
        'Bassirou',
        'Basséna',
        'Bathie',
        'Bay',
        'Baye',
        'Baylo',
        'Bayo',
        'Baïdi',
        'Becaye',
        'Bedo',
        'Ben Omar Badji',
        'Benjamin',
        'Bernard',
        'Bilal',
        'Bilinky',
        'Birame',
        'Birane',
        'Birima',
        'Biry',
        'Bocar',
        'Bodiel',
        'Bolikoro',
        'Bouba',
        'Boubacar',
        'Boubou',
        'Boucar',
        'Boucary',
        'Boucary Diao',
        'Bougouma',
        'Bouly',
        'Bouna',
        'Bourama',
        'Bourkhane',
        'Bouya',
        'Bransan',
        'Charles',
        'Charles Adrien',
        'Cheikh',
        'Cheikh Abdou Khadre',
        'Cheikh Omar',
        'Cheikh Saadibou',
        'Cheikhna',
        'Cherif',
        'Christian',
        'Chérif',
        'Ciré',
        'Colins',
        'Coly',
        'Cyril',
        'César',
        'Dalla',
        'Dallah',
        'Daly',
        'Damasoo',
        'Dame',
        'Dame Sall',
        'Damel',
        'Damé',
        'Daouda',
        'Daour',
        'David',
        'David Maurice',
        'Demb',
        'Demba',
        'Denis',
        'Diadie',
        'Diae',
        'Diagne',
        'Diakhou',
        'Dial',
        'Dialamba',
        'Dialegueye',
        'Diamanka',
        'Dianco',
        'Diaw',
        'Dicory',
        'Diegane',
        'Diere',
        'Dierry',
        'Diewo',
        'Dino',
        'Dio',
        'Diokel',
        'Diokine',
        'Diomaye',
        'Diongue',
        'Dior',
        'Diosh',
        'Disy',
        'Diène',
        'Diégane',
        'Djibo',
        'Djibril',
        'Djibril Sianfeny',
        'Djibson',
        'Djiby',
        'Djighaly Dembo',
        'Djily',
        'Djimba',
        'Djimoukor',
        'Djyby',
        'Dominik',
        'Doro',
        'Doudou',
        'Dramane',
        'Déme',
        'Dényanké',
        'Edmundo',
        'Edouard',
        'El Hadj',
        'El Hadj Ibrahima',
        'El Hadji',
        'El Hadji Babacar',
        'El Hadji Farba',
        'El Hadji Mamadou',
        'El-Hadji Boubacar',
        'Elage',
        'Elhadj Adio',
        'Elhadji',
        'Elhadji Diankha',
        'Elie Sianoune',
        'Elimane',
        'Emmanuel',
        'Faba',
        'Facourou',
        'Fadel',
        'Falilou',
        'Fall',
        'Fallou',
        'Famara',
        'Farba',
        'Fatel',
        'Fodey',
        'Fodié',
        'Fodé',
        'Fodé Ndiaye',
        'Foulah',
        'Frédéric',
        'Gabriel',
        'Galaye',
        'Gallo',
        'Gaoussou',
        'Gaspard',
        'Gaston',
        'Gaston Joseph',
        'Gawane',
        'Georges',
        'Gilbert',
        'Gora',
        'Gorgui',
        'Gormack',
        'Goumbo',
        'Goundo',
        'Grime',
        'Guidado',
        'Guillaume',
        'Habib',
        'Hadiya',
        'Hady',
        'Hamid',
        'Hamidou',
        'Hammel',
        'Hatab',
        'Henri',
        'Hima',
        'Honoré',
        'Horeb',
        'Hubert Martin',
        'Hyacinthe',
        'Iba',
        'Ibou',
        'Iboula',
        'Ibra',
        'Ibrahima',
        'Ibrahima Racine',
        'Ibrahime',
        'Idrissa',
        'Insa',
        'Isidore',
        'Ismael',
        'Ismaila',
        'Ismaïl',
        'Ismaïla',
        'Issa',
        'Isshaga',
        'Ives',
        'Jack',
        'Jacques',
        'Jamuyon',
        'Jankebay',
        'Jean Firmin',
        'Jean Jacques',
        'Jean Paul',
        'Jerome',
        'Joe',
        'Joseph',
        'Joseph David',
        'Joseph Maurice',
        'Jules',
        'Julien',
        'Justin',
        'Kader',
        'Kainack',
        'Kalidou',
        'Kalilou',
        'Kaliste',
        'Kaly',
        'Kambia',
        'Kao',
        'Kaourou',
        'Karamo',
        'Karim',
        'Kelountang',
        'Khadim',
        'Khadir',
        'Khalifa',
        'Khalil',
        'Khamby',
        'Kharagne',
        'Khary',
        'Khoudia',
        'Khoule',
        'Kola',
        'Kor',
        'Koutoubo',
        'Kyrie',
        'Kéba',
        'Lamiine',
        'Lamine',
        'Lammine',
        'Lamp',
        'Landing',
        'Lassana',
        'Latif',
        'Latsouck',
        'Latyr',
        'Laurent',
        'Laye',
        'Leyti',
        'Libasse',
        'Limane',
        'Loufa',
        'Louis Pascal',
        'Loumboul',
        'Luciano',
        'Lywa',
        'Lémou',
        'Léou',
        'Maba',
        'Macky',
        'Macodou',
        'Mactar',
        'Mademba',
        'Madia',
        'Madické',
        'Madior',
        'Mady',
        'Maffal',
        'Mafou',
        'Magath',
        'Magatte',
        'Maguette',
        'Mahamed',
        'Mahanta',
        'Mahecor',
        'Mahécor',
        'Makan',
        'Makirou',
        'Mala',
        'Malal',
        'Malamine',
        'Malang',
        'Malaw',
        'Malcolm',
        'Malick',
        'Malick Maasta Sagna',
        'Malick Tine',
        'Mallé',
        'Mama Samba',
        'Mamadou',
        'Mamadou Abass',
        'Mamadou Ba',
        'Mamadou Bamba',
        'Mamadou Daffe',
        'Mamadou Hady',
        'Mamadou Lamine',
        'Mamadou Moustapha',
        'Mamdy',
        'Mame',
        'Mame Thierno',
        'Mamour',
        'Mansor',
        'Mansour',
        'Maodo',
        'Mapaté',
        'Mar',
        'Mara',
        'Marcel',
        'Martin',
        'Massamba',
        'Massar',
        'Masseck',
        'Matar',
        'Mathieu',
        'Mathieu Gerard',
        'Maximuss',
        'Mayoro Tidiane',
        'Mbagnick',
        'Mbakhane',
        'Mbamoussa',
        'Mbar',
        'Mbaye',
        'Mbaye Ndiaye',
        'Mbissane',
        'Medzo',
        'Meissa',
        'Meïssa',
        'Michél',
        'Mika',
        'Modou',
        'Mody',
        'Mohamed',
        'Mohamed Attahane',
        'Moise',
        'Moize',
        'Moktar',
        'Momar',
        'Momo',
        'Mor',
        'Mor Awa',
        'Mor Niang',
        'Mortalla',
        'Moth',
        'Mouhagerrard',
        'Mouhamad Youssouph',
        'Mouhamadou',
        'Mouhamadou Baylo',
        'Mouhamadou Lamine',
        'Mouhamadou Moustapha',
        'Mouhamed',
        'Mountaga',
        'Moussa',
        'Moussa Mane',
        'Moustafa',
        'Moustapha',
        'Moustapha Anne',
        'Moustapha Cissé',
        'Moustapha Dem',
        'Muhamed',
        'Mébok',
        'Médoune',
        'Namori',
        'Nassimento',
        'Ndane',
        'Ndar',
        'Ndataly',
        'Ndiack',
        'Ndiaga',
        'Ndiankou',
        'Ndiasse',
        'Ndiaw',
        'Ndiawar',
        'Ndiaya',
        'Ndiogou',
        'Ndiouga',
        'Ndongo',
        'Nestor',
        'Neveras',
        'Ngagne',
        'Ngor',
        'Nguénar',
        'Niaka',
        'Niakar',
        'Niankou',
        'Nicolas',
        'Niokhor',
        'Nouh',
        'Nouha',
        'Npaly',
        'Omar',
        'Omar Batama',
        'Oumar',
        'Ousmane',
        'Ousseynou',
        'Pakar',
        'Papa',
        'Papa Abdoulaye',
        'Papa Amadou',
        'Papa Lamine',
        'Papa Leye',
        'Papa Libasse',
        'Papa Ndiaga',
        'Papa Ousmane',
        'Papa Saliou',
        'Pape',
        'Pape Alioune Sow',
        'Pape Amadou',
        'Pape Demba',
        'Pape Djiby',
        'Pape Malick',
        'Pape Matar',
        'Pape Mbaba Ndiaye',
        'Pape Mbaye',
        'Pape Yoro',
        'Papis',
        'Papo',
        'Papy',
        'Pathé',
        'Patrice',
        'Paul',
        'Pierre',
        'Pierre Marie',
        'Pita',
        'Pitagone',
        'Popol',
        'Prosper',
        'Pythagore',
        'Racina',
        'Racine',
        'Rahael',
        'Raphaël',
        'Redie',
        'Rifo',
        'Robert',
        'Robert Thomas',
        'Roland',
        'Sacoura',
        'Sada Hamady',
        'Sada Mamadou',
        'Sadibou',
        'Sadikhe',
        'Sahaba',
        'Sakhir',
        'Salam',
        'Salif',
        'Saliou',
        'Sall',
        'Salomon',
        'Saloum',
        'Samba',
        'Samori',
        'Samsidine',
        'Sana',
        'Sandigui',
        'Sankoun',
        'Sanokho',
        'Sasane',
        'Saturnin Lucas',
        'Saydou',
        'Saër',
        'Saïdou',
        'Seckhou',
        'Sellou',
        'Semou',
        'Senghane',
        'Serigne',
        'Serigne Fallou',
        'Serigne Saliou',
        'Seyba',
        'Seydina',
        'Seydou',
        'Sheikh',
        'Sibiloumbaye',
        'Sidate',
        'Sidy',
        'Sidy Mohamed',
        'Sihalébé',
        'Sihounke',
        'Silly',
        'Silouane',
        'Simon Diémé',
        'Siéka',
        'Socé',
        'Sogui',
        'Soireba',
        'Solal',
        'Sonar',
        'Sophie',
        'Soriba',
        'Souberou',
        'Souleye',
        'Souleyemane',
        'Souleymane',
        'Soundjata',
        'Sounkarou',
        'Souty',
        'Stephane',
        'Sécouba',
        'Sédar',
        'Sékou',
        'Tafsir',
        'Takha',
        'Talla',
        'Tamsir',
        'Tanor',
        'Tapha',
        'Tayfor',
        'Tekheye',
        'Theophile',
        'Thiam',
        'Thiarro',
        'Thiawlo',
        'Thiendela',
        'Thierno',
        'Thione',
        'Thiousso',
        'Tidiane',
        'Tidjane',
        'Tijane',
        'Tony',
        'Toumani',
        'Toumany',
        'Tété',
        'Vieux',
        'Vincent',
        'Wagane',
        'Wahab',
        'Waly',
        'Wandifing',
        'Wasis',
        'Weazea',
        'Willer',
        'Woula',
        'Woury',
        'Yacine',
        'Yacouba',
        'Yafaye',
        'Yakou',
        'Yamar',
        'Yancouba',
        'Yankhoba',
        'Yelly',
        'Yerim',
        'Yero',
        'Yoro',
        'Youga',
        'Yougo',
        'Younouss',
        'Youssef',
        'Youssou',
        'Youssouf',
        'Youssoufa',
        'Youssouph',
        'Zale',

    );

    public static $womanFirstNames = array(
        'Abanda',
        'Abibatou',
        'Abide',
        'Absa',
        'Aby',
        'Ada',
        'Adama',
        'Adiouma',
        'Adja',
        'Adji',
        'Agnes',
        'Aicha',
        'Aichatou',
        'Aida',
        'Aisha',
        'Aissa',
        'Aissata',
        'Aissatou',
        'Akinumelob',
        'Alias',
        'Alima',
        'Alimatou',
        'Alinsiitowe',
        'Aloendisso',
        'Altine',
        'Ama',
        'Amaka',
        'Ami',
        'Amianta',
        'Amie',
        'Amina',
        'Aminata',
        'Aminata Dior',
        'Amsatou',
        'Amy',
        'Amyna',
        'Angel',
        'Angéle Yissé',
        'Anita',
        'Anitah',
        'Anna',
        'Anne Celestine',
        'Annie Claude',
        'Anshal',
        'Anta',
        'Aram',
        'Arame',
        'Assa',
        'Assietou',
        'Astou',
        'Astou Ba',
        'Ata',
        'Atia',
        'Audra',
        'Awa',
        'Awa Fatty',
        'Awa Ndao',
        'Awentorébé',
        'Ayimpen',
        'Azaima',
        'Aïcha',
        'Aïda',
        'Aïssatou',
        'Badji',
        'Banel',
        'Batouly',
        'Bigué',
        'Bijou',
        'Billé',
        'Bineta',
        'Binetou',
        'Binette',
        'Binou Laye',
        'Binoush',
        'Binta',
        'Bintou',
        'Bodiel',
        'Boirika',
        'Bougouma',
        'Boury',
        'Bousso',
        'Charlotte',
        'Choupette',
        'Christie',
        'Ciramadi',
        'Ciré',
        'Claire',
        'Clara',
        'Codou',
        'Combé',
        'Corinne',
        'Coumba',
        'Coumba Nor',
        'Coumboye',
        'Coura',
        'Cynthia',
        'Cyrille Marie Irene',
        'Daba',
        'Dabo Laye',
        'Dado',
        'Daka',
        'Daly',
        'Daniella',
        'Daro',
        'Daso',
        'Debbo',
        'Deborah',
        'Dewel',
        'Dewene',
        'Diadji',
        'Diaga',
        'Diakher',
        'Diakhou',
        'Dialikatou',
        'Diama',
        'Diambal',
        'Diamila',
        'Diangou',
        'Dianké',
        'Dianna',
        'Diara',
        'Diariatou',
        'Diarra',
        'Diarri',
        'Diary',
        'Diatou',
        'Dibor',
        'Didi',
        'Dieourou',
        'Dieyna',
        'Diha',
        'Dija',
        'Dina',
        'Dior',
        'Dioro',
        'Diouma',
        'Diéry',
        'Djaly',
        'Djeynaba',
        'Djilane',
        'Djébou',
        'Dkikel',
        'Dominiqua',
        'Doris',
        'Dykha',
        'Défa',
        'Edwige',
        'Ella',
        'Ellen',
        'Emairence',
        'Emelita',
        'Enfadima',
        'Estrilian',
        'Eva',
        'Eveline',
        'Fabala',
        'Fabinta',
        'Fadima',
        'Fakane',
        'Fall',
        'Fama',
        'Fanta',
        'Farmata',
        'Fathy',
        'Fatim',
        'Fatima',
        'Fatima Zahra',
        'Fatimah',
        'Fatma',
        'Fatou',
        'Fatou Bintou',
        'Fatou Cix',
        'Fatou Kine',
        'Fatoumata',
        'Fatoumata Diabu',
        'Fatoumatou',
        'Fatounding',
        'Fatu',
        'Fifi',
        'Fily',
        'Flore',
        'Fčlicia',
        'Gagneciry',
        'Garmi',
        'Gift',
        'Gift Sow',
        'Gina',
        'Gnagna',
        'Gnilane',
        'Gnima',
        'Gniminha',
        'Good',
        'Gouya',
        'Guignane',
        'Guissaly',
        'Guęta',
        'Habibatou',
        'Haby',
        'Hawa',
        'Heinda',
        'Henriette',
        'Holèl',
        'Houma Binta Bodian',
        'Iris',
        'Ismaila',
        'Issate',
        'Jeanne',
        'Kadiali',
        'Kadijatou',
        'Kankou',
        'Karimatou',
        'Keen',
        'Kenbougoul',
        'Khadi',
        'Khadidiatou',
        'Khadija',
        'Khadijatou',
        'Khady',
        'Khar',
        'Khardiatou',
        'Khary',
        'Khayfatte',
        'Khoudia',
        'Khoudjedji',
        'Khoumbaré',
        'Khoyane',
        'Kiara',
        'Kine',
        'Kiné',
        'Kita',
        'Kole Loume',
        'Korka',
        'Kéwé',
        'Laffia',
        'Lafia',
        'Lama',
        'Leyla',
        'Lika',
        'Linda',
        'Lissah',
        'Liwane',
        'Lonely',
        'Louise Bernadette',
        'Loumbel',
        'Lucy',
        'Luna',
        'Léa',
        'Léa Mélia',
        'Léna',
        'Mada',
        'Madeleine',
        'Madina',
        'Madior',
        'Madjiguène',
        'Madjiguéne Badiane',
        'Madjigučne',
        'Maguette',
        'Magui',
        'Mahawa',
        'Maicha',
        'Maimouna',
        'Malisa',
        'Mama',
        'Mamadou',
        'Mamassa',
        'Mame',
        'Mame Diarra',
        'Mame Fatou',
        'Mame Mareme',
        'Mami',
        'Mamina',
        'Mamish',
        'Mamy',
        'Mane',
        'Manthita',
        'Mareme',
        'Maria',
        'Maria Faustine',
        'Mariama',
        'Mariane',
        'Marianne',
        'Marie',
        'Marie Aicha',
        'Marie André',
        'Marie Claire',
        'Marie Claude',
        'Marie Jeanne',
        'Marie Lou',
        'Marie Therese',
        'Marie Thomas',
        'Marieme',
        'Marina',
        'Mariéma',
        'Marry',
        'Marème',
        'Matty',
        'Maty',
        'Maya',
        'Mayalen',
        'Mayatta',
        'Maymouna',
        'Maďmouna Badiane',
        'Mbacké',
        'Mbarou',
        'Mbayang',
        'Mbayeng',
        'Mbissine',
        'Mbossé',
        'Me',
        'Meïssa',
        'Michelle',
        'Mickaela',
        'Mickaelle',
        'Mima',
        'Mimi',
        'Mingue',
        'Monica',
        'Mouna',
        'Mounass',
        'Mouskéba',
        'Moussou',
        'Ndiémé',
        'Nabou',
        'Nafi',
        'Nafissatou',
        'Nafiza',
        'Namina',
        'Nancy',
        'Naomi',
        'Nathylia',
        'Nazarene',
        'Nbieumbet',
        'Ndebane',
        'Ndella',
        'Ndeya',
        'Ndeye',
        'Ndeye Aida Mbene',
        'Ndeye Aita',
        'Ndeye Bougouma',
        'Ndeye Khady',
        'Ndeye Maguette Ba',
        'Ndeye Sy',
        'Ndeye Yacine',
        'Ndiarenioul',
        'Ndiarka',
        'Ndiasse',
        'Ndiaty',
        'Ndiaye',
        'Ndioba',
        'Ndiolé',
        'Ndioro',
        'Ndoffène',
        'Ndombo',
        'Neyba',
        'Ngoné',
        'Ngosse',
        'Ngoundj',
        'Nguenar',
        'Nguissaly',
        'Niakuhufosso',
        'Niali',
        'Nialine',
        'Ningou',
        'Nini',
        'Niouma',
        'Nogoye',
        'Nola',
        'Nuna',
        'Néné',
        'Odette',
        'Oly',
        'Ornella',
        'Oulimata',
        'Ouly',
        'Oulèye',
        'Oumane',
        'Oumou',
        'Oumou Khairy',
        'Oumy',
        'Oumy Sene',
        'Oureye',
        'Ouria',
        'Ouy',
        'Patient',
        'Paulette',
        'Paulette Melaine',
        'Pauline',
        'Penda',
        'Penda Cisse',
        'Penda Ka',
        'Peye-Peye',
        'Philomene',
        'Phoebé Mariane Mamor',
        'Pierrette',
        'Raby',
        'Raki',
        'Rama',
        'Ramata',
        'Ramatoulaye',
        'Rebecca',
        'Reine',
        'Rita Raicha',
        'Rokhaya',
        'Rokhya',
        'Roky',
        'Rosa',
        'Rosaline',
        'Rose Binta',
        'Roubba',
        'Roughy',
        'Rougui',
        'Ruby',
        'Ruth Esther',
        'Sabrina',
        'Sadio',
        'Safi',
        'Safiétou',
        'Sagar',
        'Sahaba',
        'Salamata',
        'Salimata',
        'Salma',
        'Saly',
        'Sanakha',
        'Sanou',
        'Saoudatou',
        'Sarah',
        'Sarratou',
        'Sasha',
        'Sawdiatou',
        'Selbé',
        'Sell',
        'Seynabou',
        'Seyni',
        'Shammy',
        'Shanya',
        'Sibett',
        'Siga',
        'Sira',
        'Sirabiry',
        'Soda',
        'Sofiatou',
        'Sofie',
        'Sofietou',
        'Sokhna',
        'Sonar',
        'Sonia',
        'Sophie',
        'Souade',
        'Souadou',
        'Soukeye',
        'Soukeyna',
        'Souleymane',
        'Suzanne',
        'Suzzy',
        'Syana',
        'Tabara',
        'Tacko',
        'Taki',
        'Tania',
        'Tening',
        'Tessa',
        'Thiaba',
        'Thiomba',
        'Thiony',
        'Thioro',
        'Thioumbane',
        'Thérèse',
        'Tiné',
        'Tocka',
        'Tokoselle',
        'Toly',
        'Toufa',
        'Toufachou',
        'Tunechii',
        'Téwa',
        'Valerie',
        'Veronica',
        'Victoire',
        'Victoria',
        'Vivian',
        'Walty',
        'Wanita',
        'Yacine',
        'Yadicone',
        'Yande',
        'Yandou',
        'Yandé',
        'Yasmi',
        'Yasmine',
        'Yaye',
        'Yvette',
        'Zeina',
        'Zeyna',

    );

    /**
     *  Name generator
     *  
     * @function to generate random name
     * @return   name(String)
     */
    static function getName()
    {
        $dimension = count(self::$names);
        $random_index = random_int(0, (int)$dimension - 1);
        return self::$names[$random_index];
    }
    /**
     * FirstName generator
     * 
     * @function to generate random firstName
     * @return   firstName(String)
     */
    static function getFirstName($gender = null)
    {
        if ($gender == 'male') {
            $dimension = count(self::$manFirstNames);
            $random_index = random_int(0, (int)$dimension - 1);
            return self::$manFirstNames[$random_index];
        } elseif ($gender == 'female') {
            $dimension = count(self::$womanFirstNames);
            $random_index = random_int(0, (int)$dimension - 1);
            return self::$womanFirstNames[$random_index];
        } else {
            $dimension = count(self::$firstNames);
            $random_index = random_int(0, (int)$dimension - 1);
            return self::$firstNames[$random_index];
        }
    }
}
